import bcrypt from "bcrypt";
const data = {
  user: [
    {
      name: "tqlong1609",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234567", 8),
      isAdmin: true,
    },
    {
      name: "user1",
      email: "user1@example.com",
      password: bcrypt.hashSync("1234567", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviewer: 10,
      description: "hight quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pant",
      image: "/images/p2.jpg",
      price: 200,
      countInStock: 0,
      brand: "Pant",
      rating: 3.5,
      numReviewer: 25,
      description: "low quality product",
    },
    {
      name: "Nike Slim Pant 2",
      category: "Pant",
      image: "/images/p3.jpg",
      price: 300,
      countInStock: 10,
      brand: "Nike",
      rating: 3,
      numReviewer: 7,
      description: "hight quality product",
    },
    {
      name: "Nike Slim White Pant",
      category: "Pant",
      image: "/images/p4.jpg",
      price: 400,
      countInStock: 0,
      brand: "Puma",
      rating: 1.5,
      numReviewer: 40,
      description: "Low quality product",
    },
    {
      name: "Nike White Shirt 1",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 150,
      countInStock: 10,
      brand: "Nike",
      rating: 4.3,
      numReviewer: 34,
      description: "hight quality product",
    },
    {
      name: "Nike Slim Shirt 2",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: 400,
      countInStock: 10,
      brand: "Adidas",
      rating: 5,
      numReviewer: 50,
      description: "hight quality product",
    },
  ],
};

export default data;
