export enum ECartItems {
    ADD_PRODUCT_CART = 'ADD_PRODUCT_CART',
    REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART',
    SHIPPING_ADDRESS = 'SHIPPING_ADDRESS',
    PAYMENT_METHOD = 'PAYMENT_METHOD',
    CART_EMPTY = 'CART_EMPTY'
}