export enum EOrderDetail {
    'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST',
    'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS',
    'GET_ORDER_FAIL' = 'GET_ORDER_FAIL',

    'GET_ORDER_PAYMENT_REQUEST' = 'GET_ORDER_PAYMENT_REQUEST',
    'GET_ORDER_PAYMENT_SUCCESS' = 'GET_ORDER_PAYMENT_SUCCESS',
    'GET_ORDER_PAYMENT_FAIL' = 'GET_ORDER_PAYMENT_FAIL',
    'GET_ORDER_PAYMENT_RESET' = 'GET_ORDER_PAYMENT_RESET',

}