export enum EPlaceOrder {
    'PLACE_ORDER_REQUEST' = 'PLACE_ORDER_REQUEST',
    'PLACE_ORDER_SUCCESS' = 'PLACE_ORDER_SUCCESS',
    'PLACE_ORDER_FAIL' = 'PLACE_ORDER_FAIL',
    'PLACE_ORDER_RESET' = 'PLACE_ORDER_RESET',
}