export enum EProductList {
    PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST",
    PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL",

    PRODUCT_LIST_SORT_DECREASE_REQUEST = 'PRODUCT_LIST_SORT_DECREASE_REQUEST',
    PRODUCT_LIST_SORT_DECREASE_SUCCESS = 'PRODUCT_LIST_SORT_DECREASE_SUCCESS',
    PRODUCT_LIST_SORT_DECREASE_FAIL = 'PRODUCT_LIST_SORT_DECREASE_FAIL',

    LATEST_PRODUCT_LIST_SORT_DECREASE_REQUEST = 'LATEST_PRODUCT_LIST_SORT_DECREASE_REQUEST',
    LATEST_PRODUCT_LIST_SORT_DECREASE_SUCCESS = 'LATEST_PRODUCT_LIST_SORT_DECREASE_SUCCESS',
    LATEST_PRODUCT_LIST_SORT_DECREASE_FAIL = 'LATEST_PRODUCT_LIST_SORT_DECREASE_FAIL'
}

