export enum EUser {
    'SIGN_IN_REQUEST' = 'SIGN_IN_REQUEST',
    'SIGN_IN_SUCCESS' = 'SIGN_IN_SUCCESS',
    'SIGN_IN_FAIL' = 'SIGN_IN_FAIL',

    'REGISTER_USER_REQUEST' = 'REGISTER_USER_REQUEST',
    'REGISTER_USER_SUCCESS' = 'REGISTER_USER_SUCCESS',
    'REGISTER_USER_FAIL' = 'REGISTER_USER_FAIL',

    'PROFILE_USER_REQUEST' = 'PROFILE_USER_REQUEST',
    'PROFILE_USER_SUCCESS' = 'PROFILE_USER_SUCCESS',
    'PROFILE_USER_FAIL' = 'PROFILE_USER_FAIL',

    'SIGN_OUT' = 'SIGN_OUT',
}